# Generated by Django 5.0.6 on 2024-06-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='subtitle',
            field=models.CharField(max_length=200),
        ),
    ]
