# Generated by Django 5.0.6 on 2024-07-04 14:11

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_images/default_avatar.png', null=True, upload_to=main.models.user_directory_path),
        ),
    ]
