# Generated by Django 5.0.6 on 2024-06-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_create_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/ferjen/image/upload/v1718991742/avatars/red_cuddly_iqxage.png', null=True, upload_to='profile_images/'),
        ),
    ]
